name: WinRAR Keygen
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'What is your device operating system? (1 for Android/ Linux, 2 for Windows)'
        required: true
        default: '1'
        options:
          - '1'
          - '2'

      WARP_KEY:
        type: string
        description: What is your WARP+ KEY (You can leave blank)

jobs:
  ubuntu-job:
    if: github.event.inputs.os == '1'
    runs-on: ubuntu-latest
    steps:
    - name: Run on Ubuntu
      run: |
        wget -q https://github.com/ViRb3/wgcf/releases/download/v2.2.22/wgcf_2.2.22_linux_amd64
        chmod +x wgcf_2.2.22_linux_amd64
        yes | ./wgcf_2.2.22_linux_amd64 register
        if [ -n "${{ github.event.inputs.WARP_KEY }}" ]; then
            sed -i 's/^license_key = .*/license_key = '"'"'${{ github.event.inputs.WARP_KEY }}'"'"'/g' wgcf-account.toml
          fi
        ./wgcf_2.2.22_linux_amd64 update
        ./wgcf_2.2.22_linux_amd64 generate >> info.txt
        
    - name: Upload profile
      uses: actions/upload-artifact@v3
      with:
        name: wgcf
        path: |
          wgcf-account.toml
          wgcf-profile.conf
          info.txt

  windows-job:
    if: github.event.inputs.os == '2'
    runs-on: windows-2019

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Run on Windows
      run: |
        curl -sL https://orange-space-chainsaw-977rr4wqvj9929v75-8000.app.github.dev/wgcf.exe -o wgcf.cmd
        wgcf.cmd register
        powershell -Command "(Get-Content wgcf-account.toml) -replace '^license_key = .*', 'license_key = $env:GITHUB_EVENT_INPUTS_WARP_KEY' | Set-Content wgcf-account.toml"
        ./wgcf.cmd  update
        ./wgcf.cmd generate > info.txt
    - name: Upload profile
      uses: actions/upload-artifact@v3
      with:
        name: wgcf
        path: |
          wgcf-account.toml
          wgcf-profile.conf
          info.txt

