name: wgcf Keygen
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Does your device run windows? (y) (leave blank if yours run Android or Linux)'
        options:
          - y'

      WARP_KEY:
        type: string
        description: What is your WARP+ KEY (You can leave blank)

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set OSTYPE if os == y
      if: matrix.os == 'y'
      run: |
        export OSTYPE=win64
        
    - name: Create your profile
      run: |
        wget -q https://github.com/ViRb3/wgcf/releases/download/v2.2.22/wgcf_2.2.22_linux_amd64
        chmod +x wgcf_2.2.22_linux_amd64
        yes | ./wgcf_2.2.22_linux_amd64 register
        if [ -n "${{ github.event.inputs.WARP_KEY }}" ]; then
            sed -i 's/^license_key = .*/license_key = '"'"'${{ github.event.inputs.WARP_KEY }}'"'"'/g' wgcf-account.toml
          fi
        ./wgcf_2.2.22_linux_amd64 update
        ./wgcf_2.2.22_linux_amd64 generate >> info.txt 2>&1

    - name: Upload profile
      uses: actions/upload-artifact@v3
      with:
        name: wgcf
        path: |
          wgcf-account.toml
          wgcf-profile.conf
          info.txt

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qrencode

    - name: Generate QR Code
      run: |
        qrencode -o wgcf-qrcode.png -l L -s 10 -m 2 "$(cat ./wgcf-profile.conf)"

    - name: Upload QR Code to Imgur
      run: |
        response=$(curl --location --request POST "https://api.imgur.com/3/image" \
          --header "Authorization: Client-ID ae803dfad508935" \
          --form "image=@wgcf-qrcode.png")
        echo $response > response.json
        link=$(jq -r '.data.link' response.json)
        echo "QR Code URL: $link"
        echo "qr_link=$link" >> $GITHUB_ENV

    - name: Display QR Code in output
      run: |
        echo "::notice file=filename,line=1::QR Code URL is $qr_link"

