name: WinRAR Keygen
on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'What is your device operating system? (1 for Android/ Linux, 2 for Windows)'
        required: true
        default: '1'
        options:
          - '1'
          - '2'

      WARP_KEY:
        type: string
        description: What is your WARP+ KEY (You can leave blank)

jobs:
  ubuntu-job:
    if: github.event.inputs.os == '1'
    runs-on: ubuntu-latest
    steps:
    - name: Run on Ubuntu
      run: |
        wget -q https://github.com/ViRb3/wgcf/releases/download/v2.2.22/wgcf_2.2.22_linux_amd64
        chmod +x wgcf_2.2.22_linux_amd64
        yes | ./wgcf_2.2.22_linux_amd64 register
        ./wgcf_2.2.22_linux_amd64 generate
        ./wgcf_2.2.22_linux_amd64 status >> info.txt
        
    - name: Upload profile
      uses: actions/upload-artifact@v3
      with:
        name: wgcf
        path: |
          wgcf-account.toml
          wgcf-profile.conf
          info.txt

  windows-job:
    if: github.event.inputs.os == '2'
    runs-on: windows-2019
    steps:
    - name: Run on Windows
      run: |
        curl -O https://github.com/ViRb3/wgcf/releases/download/v2.2.22/wgcf_2.2.22_windows_amd64.exe
        dir
        .\wgcf_2.2.22_windows_amd64.exe register
        wgcf_2.2.22_windows_amd64 generate | tee info.txt

    - name: Upload profile
      uses: actions/upload-artifact@v3
      with:
        name: wgcf
        path: |
          wgcf-account.toml
          wgcf-profile.conf
          info.txt

